### ISSUE TITLE
Runtime error：

### ISSUE THREAD

**Issue by jessicasxl** [huanghoujing/AlignedReID-Re-Production-Pytorch#35]
我按照readme运行时，出现问题Runtime error：cuda runtime error(30)：unknown error at /pytorch/aten/src/THC/THCTensorRandom.cu:25，请问有同学遇到吗？

**Comment by huanghoujing** [comment]
你好，请问是用python2, pytorch0.3跑的吗？可以提供一下运行的命令吗？还有提供一下`nvidia-smi`命令输出的结果？

**Comment by jessicasxl** [comment]
你好，我的是Python2.7和pytorch0.3.1
运行指令是：
python script/experiment/train_ml.py \
-d '((0,), (1,))' \
-r 1 \
--num_models 2 \
--dataset market1501 \
--ids_per_batch 32 \
--ims_per_id 4 \
--normalize_feature false \
-gm 0.3 \
-glw 1 \
-llw 0 \
-idlw 0 \
-pmlw 0 \
-gdmlw 1 \
-ldmlw 0 \
--base_lr 2e-4 \
--lr_decay_type exp \
--exp_decay_at_epoch 151 \
--total_epochs 300

nvidia-smi输出为：
![nvidia-smi](https://user-images.githubusercontent.com/22634392/40954066-56a5b050-68b5-11e8-8dbf-892298f23ba5.png)

**Comment by huanghoujing** [comment]
这个命令要求使用两块显卡，可能是这个导致的错误，当访问第1号显卡时会出错，因为不存在。

**Comment by jessicasxl** [comment]
嗯嗯，是这个原因，多谢多谢！

**Comment by lufei92** [comment]
您好，我在跑您的代码的时候出现runtimeerror问题
Traceback (most recent call last):
  File "script/experiment/train_ml.py", line 850, in <module>
    main()
  File "script/experiment/train_ml.py", line 358, in main
    for _ in range(cfg.num_models)]
  File "script/experiment/train_ml.py", line 358, in <listcomp>
    for _ in range(cfg.num_models)]
  File "./aligned_reid/model/Model.py", line 12, in __init__
    self.base = resnet50(pretrained=True)
  File "./aligned_reid/model/resnet.py", line 204, in resnet50
    model.load_state_dict(remove_fc(rest))
  File "./aligned_reid/model/resnet.py", line 161, in remove_fc
    for key, value in state_dict.items():   
RuntimeError: OrderedDict mutated during iteration
在去除fc层参数这段代码出现问题def remove_fc(state_dict):
  """Remove the fc layer parameters from state_dict."""
  #print(state_dict.items())
  for key, value in state_dict.items():   
    if key.startswith('fc.'):
      del state_dict[key]
  return state_dict
我测试过，数据有读取到，在删除fc层参数这也能执行，但是整体跑下来就是会出现这个错误，请问这个问题怎么解决

**Comment by huanghoujing** [comment]
你好，这个错误应该是`remove_fc`这个函数不兼容Python 3。这个代码用Python 3可能还有其它问题，你试一下用Python 2跑.

**Comment by hsqaihkl** [comment]
@huanghoujing 你好我现在也是在remove_fc这个函数出现问题了，我的是Python3,请问有什么方法修改么？谢谢
