### ISSUE TITLE
TypeError: max() got an unexpected keyword argument 'keepdim'

### ISSUE THREAD

**Issue by xxx2974** [huanghoujing/AlignedReID-Re-Production-Pytorch#57]
I have met a problem when I trained it by  python script/experiment/train.py -d '(4,5,6)' -r 1 --dataset market1501 --ids_per_batch 32 --ims_per_id 4 --normalize_feature false -gm 0.3 -glw 1 -llw 0 -idlw 0 --base_lr 2e-4 --lr_decay_type exp --exp_decay_at_epoch 151 --total_epochs 300

the details 
Traceback (most recent call last):
  File "script/experiment/train.py", line 632, in <module>
    main()
  File "script/experiment/train.py", line 451, in main
    normalize_feature=cfg.normalize_feature)
  File "./aligned_reid/model/loss.py", line 217, in global_loss
    dist_mat, labels, return_inds=True)
  File "./aligned_reid/model/loss.py", line 161, in hard_example_mining
    dist_mat[is_pos].contiguous().view(N, -1), 1, keepdim=True)
TypeError: max() got an unexpected keyword argument 'keepdim'

Can you help me?

**Comment by Ontheway361** [comment]
dist_mat[is_pos].contiguous().view(N, -1), 1, keepdims=True) ?
